[providers]
python = "3.11"

[phases.setup]
aptPkgs = [
    "libpango-1.0-0",
    "libpangoft2-1.0-0",
    "libgobject-2.0-0",
    "libffi-dev",
    "shared-mime-info",
    "fontconfig",
    "libcairo2",
    "libpangocairo-1.0-0",
    "libgdk-pixbuf2.0-0",
    "libxml2",
    "libxslt1.1"
]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"