# Generated by Django 6.0.4 on 2026-04-22 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioBloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(verbose_name='Día')),
                ('inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('fin', models.TimeField(verbose_name='Hora de Fin')),
                ('capacidad_maxima', models.PositiveIntegerField(default=20, verbose_name='Capacidad Máxima')),
            ],
            options={
                'verbose_name': 'Bloque de Horario',
                'verbose_name_plural': 'Bloques de Horario',
                'ordering': ['dia', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='FichaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('objetivo', models.TextField(help_text='disminuir peso corporal, disminuir grasa, aumentar masa muscular etc', verbose_name='Objetivo entrenamiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Contacto telefónico/whatsapp')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('fecha_nacimiento', models.DateField()),
                ('estatura', models.PositiveIntegerField(verbose_name='Estatura (Cms.)')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso (Kgs.)')),
                ('ocupacion', models.CharField(max_length=200, verbose_name='Ocupación o trabajo')),
                ('dias_semanales', models.CharField(max_length=50, verbose_name='Días de entrenamiento semanal (cantidad)')),
                ('horario_preferente', models.CharField(max_length=100, verbose_name='Horario del día en que entrena preferentemente')),
                ('experiencia', models.CharField(max_length=200, verbose_name='Experiencia en entrenamiento (hace cuanto entrena)')),
                ('deporte_previo', models.CharField(blank=True, max_length=200, verbose_name='Deporte que practica o alguna vez practicó')),
                ('comida_favorita', models.CharField(blank=True, max_length=255, verbose_name='Comida favorita (o preferencia, dulce, salado etc)')),
                ('intolerancias', models.TextField(blank=True, verbose_name='Comida que le haga mal o que no puede comer')),
                ('alimentos_diarios', models.TextField(blank=True, verbose_name='¿Qué alimentos le acomoda ingerir diariamente?')),
                ('medicacion', models.CharField(blank=True, max_length=255, verbose_name='¿Consume algún tipo de medicación? ¿Cual?')),
                ('drogas', models.CharField(blank=True, max_length=255, verbose_name='¿Consume algún tipo de droga habitual o socialmente?')),
                ('dieta_tiempo', models.CharField(blank=True, max_length=200, verbose_name='¿Hace cuánto se alimenta de esta forma?')),
                ('comida_desayuno', models.TextField(blank=True, verbose_name='Desayuno')),
                ('comida_snack1', models.TextField(blank=True, verbose_name='Snack o colación')),
                ('comida_almuerzo', models.TextField(blank=True, verbose_name='Almuerzo')),
                ('comida_once', models.TextField(blank=True, verbose_name='Once o colación')),
                ('comida_cena', models.TextField(blank=True, verbose_name='Cena o ultima comida del dia')),
                ('lesiones', models.TextField(blank=True, verbose_name='Lesiones, problemas, operación/tratamiento médico')),
                ('enfermedades_familiares', models.TextField(blank=True, verbose_name='Enfermedades/patologías familiares')),
                ('hora_despertar', models.TimeField(blank=True, null=True, verbose_name='¿A qué hora usted generalmente se despierta o levanta?')),
                ('hora_dormir', models.TimeField(blank=True, null=True, verbose_name='¿a qué hora usted generalmente se duerme o acuesta?')),
                ('suplementos', models.TextField(blank=True, verbose_name='Suplementos que ha consumido, tiempo y administración')),
                ('comentario_adicional', models.TextField(blank=True, verbose_name='Comentario adicional')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ficha', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Alumno',
                'verbose_name_plural': 'Fichas de Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='reservas.fichaalumno')),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_bloque', to='reservas.horariobloque')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('alumno', 'bloque')},
            },
        ),
    ]
