# Generated by Django 6.0.4 on 2026-04-22 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariobloque',
            name='tipo',
            field=models.CharField(choices=[('ENTRENAMIENTO', 'Entrenamiento'), ('NUTRICION', 'Nutrición')], default='ENTRENAMIENTO', max_length=20),
        ),
    ]
