# Generated by Django 6.0.4 on 2026-04-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_horariobloque_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='plan_kinesiologia',
            field=models.BooleanField(default=False, verbose_name='Habilitar Kinesiología'),
        ),
        migrations.AddField(
            model_name='fichaalumno',
            name='plan_nutricional',
            field=models.BooleanField(default=False, verbose_name='Habilitar Nutrición'),
        ),
    ]
