# Generated by Django 6.0.4 on 2026-04-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_fichaalumno_plan_kinesiologia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='plan',
            field=models.CharField(choices=[('4_CLASES', '4 Clases ($30.000) - 1 vez x semana'), ('8_CLASES', '8 Clases ($40.000) - 2 veces x semana'), ('12_CLASES', '12 Clases ($50.000) - 3 veces x semana'), ('16_CLASES', '16 Clases ($55.000) - 4 veces x semana'), ('FULL_20', 'FULL 20 ($60.000) - 5 veces x semana'), ('PASE_DIARIO', 'Pase Diario ($8.000)'), ('SOLO_CLINICA', 'Solo Servicios Clínicos (Sin Gym)')], default='4_CLASES', max_length=20),
        ),
    ]
