# Generated by Django 6.0.4 on 2026-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_fichaalumno_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichaalumno',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
